services:
  
  swag-guard:
    build: .
    command: ["/app", "guard"]
    restart: unless-stopped
    environment:
      - SWAG_CONTAINER=swag
      - UI_USER=admin
      - UI_PASS=password
      - LISTEN=0.0.0.0:2375
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [swag-net]

  swag-ui:
    build: .
    restart: unless-stopped
    environment:
      - SWAG_CONTAINER=swag
      - DOCKER_HOST=tcp://swag-guard:2375
      - UI_USER=admin
      - UI_PASS=password
    volumes:
      - /var/lib/docker/volumes/dockhand_data/_data/stacks/NL/let-s-encrypt-swag/config:/config   # без docker.sock
    ports:
      - 8080:8080
    networks: [default, swag-net]

networks:
  swag-net:
    internal: true
