services:
  
  swag-guard:
    image: ghcr.io/pushkinmazila2/swag-ui:latest
    entrypoint: ["/swagui", "guard"]
    restart: unless-stopped
    environment:
      - SWAG_CONTAINER=swag
      - UI_USER=admin
      - UI_PASS=${UI_PASS}
      - LISTEN=0.0.0.0:2375
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [swag-net]

    healthcheck:
      test: ["CMD-SHELL", "cat < /dev/null > /dev/tcp/127.0.0.1/2375"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  swag-ui:
    image: ghcr.io/pushkinmazila2/swag-ui:latest
    restart: unless-stopped
    environment:
      - SWAG_CONTAINER=swag
      - DOCKER_HOST=tcp://swag-guard:2375
      - UI_USER=admin
      - UI_PASS=${UI_PASS}
    volumes:
      - ${SWAG_CONFIG_PATH}:/config
    ports:
      - 8080:8080
    networks: [default, swag-net]
    healthcheck:
      test: ["CMD-SHELL", "cat < /dev/null > /dev/tcp/127.0.0.1/8080"]
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  swag-net:
    internal: true
